server:
  port: 8085
  error:
    whitelabel:
      enabled: false
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      routes:
        - id: some_routes
          uri: https://httpbin.org/
          predicates:
             - Path=/status/**
